// src/api/mockItems.ts
import { Item } from "@/types/item";

export const mockItems: Item[] = [
  {
    item_id: 1,
    item_sku: "B155",
    item_name: "Item Name 1",
    item_color: "Black",
    item_size: "Small",
    item_quantity: 1000,
    updated_at: new Date(Date.now()), 
  },
  {
    item_id: 2,
    item_sku: "B156",
    item_name: "Item Name 2",
    item_color: "Blue",
    item_size: "Medium",
    item_quantity: 500,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 3,
    item_sku: "B157",
    item_name: "Item Name 3",
    item_color: "Red",
    item_size: "Large",
    item_quantity: 300,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 4,
    item_sku: "B158",
    item_name: "Item Name 4",
    item_color: "Green",
    item_size: "Small",
    item_quantity: 850,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 5,
    item_sku: "B159",
    item_name: "Item Name 5",
    item_color: "Yellow",
    item_size: "Medium",
    item_quantity: 600,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 6,
    item_sku: "B160",
    item_name: "Item Name 6",
    item_color: "Purple",
    item_size: "Large",
    item_quantity: 250,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 7,
    item_sku: "B161",
    item_name: "Item Name 7",
    item_color: "Pink",
    item_size: "Small",
    item_quantity: 200,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 8,
    item_sku: "B162",
    item_name: "Item Name 8",
    item_color: "Orange",
    item_size: "Medium",
    item_quantity: 450,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 9,
    item_sku: "B163",
    item_name: "Item Name 9",
    item_color: "Brown",
    item_size: "Large",
    item_quantity: 150,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 10,
    item_sku: "B164",
    item_name: "Item Name 10",
    item_color: "Gray",
    item_size: "Small",
    item_quantity: 300,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 11,
    item_sku: "B165",
    item_name: "Item Name 11",
    item_color: "Black",
    item_size: "Medium",
    item_quantity: 700,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 12,
    item_sku: "B166",
    item_name: "Item Name 12",
    item_color: "Blue",
    item_size: "Large",
    item_quantity: 900,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 13,
    item_sku: "B167",
    item_name: "Item Name 13",
    item_color: "Red",
    item_size: "Small",
    item_quantity: 400,
    updated_at: new Date(Date.now()),
  },
  {
    item_id: 14,
    item_sku: "B168",
    item_name: "Item Name 14",
    item_color: "Green",
    item_size: "Medium",
    item_quantity: 250,
    updated_at: new Date(Date.now()),
  },
];
